#ifndef CHAT_PROTOCOL_H
#define CHAT_PROTOCOL_H

#define BUF_SIZE 4096
#define MAX_NAME 64

#define STATUS_ACTIVE "ACTIVO"
#define STATUS_BUSY "OCUPADO"
#define STATUS_INACTIVE "INACTIVO"

#define T_REGISTER "REGISTER"
#define T_BROADCAST "MSG_BROADCAST"
#define T_DIRECT "MSG_DIRECT"
#define T_LIST "LIST_USERS"
#define T_GET_INFO "GET_USER_INFO"
#define T_CHANGE_STATUS "CHANGE_STATUS"
#define T_DISCONNECT "DISCONNECT"

#define T_OK "OK"
#define T_ERROR "ERROR"
#define T_SRV_BROADCAST "SERVER_BROADCAST"
#define T_SRV_DIRECT "SERVER_DIRECT"
#define T_USER_LIST "USER_LIST"
#define T_USER_INFO "USER_INFO"
#define T_STATUS_UPDATE "STATUS_UPDATE"
#define T_FORCED_STATUS "FORCED_STATUS"
#define T_USER_JOINED "USER_JOINED"
#define T_USER_LEFT "USER_LEFT"

#define ERR_NAME_DUP "101"
#define ERR_IP_DUP "102"
#define ERR_NAME_INVALID "103"
#define ERR_USER_NF "201"
#define ERR_STATUS_BAD "301"
#define ERR_FMT "401"
#define ERR_INACTIVE "501"

#endif
